### ISSUE TITLE
是否可以支持更低版本的node

### ISSUE THREAD

**Issue by workkk98** [unplugin/unplugin-inline-enum#3]
### Clear and concise description of the problem

目前package.json的engines node字段版本是>=18。

### Suggested solution

支持更低版本的node，相关语法特性调整。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
What's your Node version? I think it can be downgraded to at least v16.

**Comment by workkk98** [comment]
> What's your Node version? I think it can be downgraded to at least v16.

大部分项目都是node v16了，我觉得可以！

**Comment by sxzz** [comment]
Done via 7ba9d5718eda45c9882d38516237e190b9924f80

**Comment by sxzz** [comment]
Supported node 16.14, released as unplugin-inline-enum@0.2.0
